services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - psql_hw:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      - db
    env_file:
      - ./docker/backend/.env
    ports:
      - 3000:3000
    platform: linux/arm64

volumes:
  psql_hw:
