# Database Deployment and ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: cluster
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres